export enum EmitTypes {
  GET_INITIAL = "GET_INITIAL",
  GET_SPELLS = "GET_SPELLS",
  NEXT = "NEXT",
  PREVIOUS = "PREVIOUS",
  ROUND_START = "ROUND_START",
  UPDATE_ALL_INITIATIVE = "UPDATE_ALL_INITIATIVE",
  DELETE_ONE_INITIATIVE = "DELETE_ONE_INITIATIVE",
  DELETE_ALL_INITIATIVE = "DELETE_ALL_INITIATIVE",
  CREATE_NEW_INITIATIVE = "CREATE_NEW_INITIATIVE",
  UPDATE_ITEM_INITIATIVE = "UPDATE_ITEM_INITIATIVE",
  UPDATE_RECORD_INITIATIVE = "UPDATE_RECORD_INITIATIVE",
  UPDATE_ALL_SPELL = "UPDATE_ALL_SPELL",
  DELETE_ONE_SPELL = "DELETE_ONE_SPELL",
  DELETE_ALL_SPELL = "DELETE_ALL_SPELL",
  CREATE_NEW_SPELL = "CREATE_NEW_SPELL",
  UPDATE_ITEM_SPELL = "UPDATE_ITEM_SPELL",
  UPDATE_RECORD_SPELL = "UPDATE_RECORD_SPELL",
  UPDATE_SESSION = "UPDATE_SESSION",
  RE_ROLL = "RE_ROLL",
  RESORT = "RESORT",
  DISCORD = "DISCORD",
  REMOVE_STATUS_EFFECT = "REMOVE_STATUS_EFFECT",
  ADD_STATUS_EFFECT = "ADD_STATUS_EFFECT"
}

export enum collectionTypes {
  INITIATIVE = "initiative",
  SPELLS = "spells",
  LOGGING = "logging",
}

export enum InitiativeContextEnums {
  INITIAL_INIT = "INITIAL_INIT",
  ADD_INITIATIVE = "ADD_INITIATIVE",
  UPDATE_INITIATIVE = "UPDATE_INITIATIVE",
  INITIATITVE_LIST = "INITIATITVE_LIST",
  NEXT = "NEXT",
  PREVIOUS = "PREVIOUS",
  RE_ROLL = "RE_ROLL",
  DISCORD_INITIATIVE = "DISCORD_INITIATIVE",
  RESORT = "RESORT",
  UPDATE_ORDER = "UPDATE_ORDER",
  REMOVE_STATUS_EFFECT = "REMOVE_STATUS_EFFECT",
  SET_CURRENT_TURN = "SET_CURRENT_TURN",
  ADD_STATUS_EFFECT = "ADD_STATUS_EFFECT",
  DELETE_INITIATIVE = "DELETE_INITIATIVE",
  ROUND_START = "ROUND_START",
}

export enum SpellContextEnums {
  INITIAL_SPELLS = "INITIAL_SPELLS",
}

export interface SocketLogging {
  error: Error
}