export enum EmitTypes {
  GET_INITIAL = "GET_INITIAL",
  NEXT = "NEXT",
  PREVIOUS = "PREVIOUS",
  ROUND_START = "ROUND_START",
  UPDATE_ONE = "UPDATE_ONE",
  UPDATE_ALL = "UPDATE_ALL",
  DELETE_ONE = "DELETE_ONE",
  DELETE_ALL = "DELETE_ALL",
  CREATE_NEW = "CREATE_NEW",
  RE_ROLL = "RE_ROLL",
  RESORT = "RESORT",
  DISCORD = "DISCORD",
  REMOVE_STATUS_EFFECT = "REMOVE_STATUS_EFFECT",
  ADD_STATUS_EFFECT = "ADD_STATUS_EFFECT"
}

export enum collectionTypes {
  INITIATIVE = "initiative",
  SPELLS = "spells",
  LOGGING = "logging",
}

export enum InitiativeContextEnums {
  INITIAL_INIT = "INITIAL_INIT",
  ADD_INITIATIVE = "ADD_INITIATIVE",
  UPDATE_INITIATIVE = "UPDATE_INITIATIVE",
  INITIATITVE_LIST = "INITIATITVE_LIST",
  NEXT = "NEXT",
  PREVIOUS = "PREVIOUS",
  RE_ROLL = "RE_ROLL",
  DISCORD_INITIATIVE = "DISCORD_INITIATIVE",
  RESORT = "RESORT",
  UPDATE_ORDER = "UPDATE_ORDER",
  REMOVE_STATUS_EFFECT = "REMOVE_STATUS_EFFECT",
  SET_CURRENT_TURN = "SET_CURRENT_TURN",
  ADD_STATUS_EFFECT = "ADD_STATUS_EFFECT",
  DELETE_INITIATIVE = "DELETE_INITIATIVE",
  ROUND_START = "ROUND_START",
}

export enum SpellContextEnums {
  INITIAL_SPELLS = "INITIAL_SPELLS",
}

export interface SocketLogging {
  error: Error
}